import { expect, test } from "@celigo/ui-core-automation";
import * as selectors from "@celigo/aut-selectors";

test.describe("TC_T26986_Test to validate that user is able to see each value in the row assigned to its respective key and appropriate data is visible on parsed output section after checking the 'First record contains headers' checkbox in http export/lookup", () => {
    test.beforeEach(async ({ io }) => {
        await io.myAccountPage.navigateTo(io.data.links.HOME_PAGE_URL);
    });
    test.skip("TC_T26986 @Zephyr-IO-T26986 @Env-All @Priority-P2", async ({ io, page }) => {
        await io.homePage.addStep("*** Navigated to home page ***");
        await io.homePage.waitForElementAttached(selectors.basePagePO.RESOURCES);
        await io.myAccountPage.navigateTo(io.data.links.EXPORTS_PAGE_URL);
        await io.homePage.addStep("*** Navigated back to export page ***");
        await io.homePage.click(selectors.basePagePO.ADD_NEW_RESOURCE);
        await io.homePage.addStep("*** Clicked on create export***");
        await io.homePage.fill(selectors.connectionsPagePO.CONNECTION_SEARCH, "Google Sheets");
        await io.homePage.addStep("*** Searched for Google Sheets application ***");
        await io.flowBuilder.loadingTime();
        await io.homePage.click(selectors.exportsPagePO.GOOGLE_SHEETS);
        await io.homePage.addStep("*** Selected Google Sheets application ***");
        await io.flowBuilder.fill(selectors.connectionsPagePO.CONNECTION_INPUT, "Sheet Parser Google Sheet connection");
        await io.homePage.addStep("*** Searched for Sheet Parser Google Sheet connection CONNECTION ***");
        await io.homePage.click(selectors.connectionsPagePO.CONNECTIONDROP0);
        await io.homePage.addStep("*** Selected Sheet Parser Google Sheet connection ***");
        await io.homePage.click(selectors.basePagePO.ADD_NAME);
        await page.keyboard.press('/');
        await io.homePage.addStep("*** Clicked on 'name' field and gave a name to our import ***");
        await io.flowBuilder.click(selectors.basePagePO.SAVE);
        await io.homePage.addStep("*** Opened the import ***");
        await io.homePage.click(selectors.exportsPagePO.ASSISTANT_META_DATA_RESOURCE);
        await io.homePage.addStep("*** Clicked on Resource field ***");
        await io.homePage.clickByText('Spreadsheets.values');
        await io.homePage.addStep("*** Selected Spreadsheets.values ***");
        await io.homePage.click(selectors.exportsPagePO.ASSISTANT_META_DATA_OPERATION);
        await io.homePage.addStep("*** Clicked on operation field ***");
        await io.homePage.clickByText('Get');
        await io.homePage.addStep("*** Clicked on GET method ***");
        await io.homePage.fill(selectors.exportsPagePO.SPREAD_SHEETS_ID, "1J8z5D49IVgyB3RAz5jgu-HfzFX1yU-9B3MKPhmWxyJA");
        await io.homePage.addStep("*** Filled the spreadsheet ID ***");
        await io.homePage.click(selectors.exportsPagePO.RANGE);
        await io.homePage.keyboard('A');
        await io.homePage.keyboard('1');
        await io.homePage.keyboard(':');
        await io.homePage.keyboard('R');
        await io.homePage.keyboard('4');
        await io.homePage.keyboard('4');
        await io.homePage.addStep("*** Filled the range field ***");
        await io.homePage.click(selectors.importPagePO.HTTP_IMPORT);
        await io.homePage.addStep("*** Clciked on HTTP view ***");
        await io.homePage.click(selectors.flowBuilderPagePO.TYPE);
        await io.homePage.addStep("*** Clciked on exporting data type ***");
        await io.homePage.clickByText('All - always export all data');
        await io.homePage.addStep("*** Clciked on all export type ***");
        await io.exportsPage.waitForElementAttached(selectors.exportsPagePO.NON_STANDARD_API_TAB);
        await io.homePage.addStep("*** Wait For Non Standard API RESPONSE patterns accordian to be in document  ***");
        await io.exportsPage.click(selectors.exportsPagePO.NON_STANDARD_API_TAB);
        await io.homePage.addStep("*** Click on  Non Standard API RESPONSE patterns accordian  ***");
        await io.exportsPage.click(selectors.exportsPagePO.HEADERCHECKBOX);
        await io.homePage.addStep("*** Checked the checkbox ***");
        await io.homePage.click(selectors.importPagePO.CLICKPREVIEW);
        await io.homePage.addStep("*** Clicked on preview ***");
        await io.assert.verifyElementContainsText(selectors.importPagePO.PREVIEWDATA, '"Status": "In Design"');
        await io.homePage.addStep("*** Checked whether we are getting correct preview data or not ***");
        await io.myAccountPage.navigateTo(io.data.links.HOME_PAGE_URL);
        await io.homePage.addStep("*** Navigated back to home page ***");
    });
});