import { test, expect } from "@celigo/ui-core-automation";
import * as selectors from "@celigo/aut-selectors";

test.describe(`@Author_sagna123 TC_T833 Verify user is able to edit/delete the Related lists in Salesforce Real time Export`, () => {
    test.beforeEach(async ({ io }) => {
        await io.myAccountPage.navigateTo(io.data.links.HOME_PAGE_URL);
    });
  test(`TC_T833 @Bug-IO-71585 Verify user is able to edit/delete the Related lists in Salesforce Real time Export @Zephyr-IO-T833 @Env-All @Priority-P2`, async ({ io, page }) => {
    await io.homePage.addStep("*** Navigated to home page ***");
    await io.homePage.goToMenu("Tools", "Flow builder");
    await io.homePage.addStep("*** Navigated to Flow builder page ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ADD_SOURCE);
    await io.homePage.addStep("*** Clicked on add export ***");
    await io.flowBuilder.fill(selectors.flowBuilderPagePO.APP_NAME_INPUT, "SALESFORCE");
    await io.homePage.addStep("*** Searched for salesforce application ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.SF);
    await io.homePage.addStep("*** Clicked on salesforce application ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.REALTIME_EXPORT_TYPE);
    await io.homePage.addStep("*** Clicked on realtime option ***");
    await io.flowBuilder.click(selectors.basePagePO.CREATE_FROM_SCRATCH);
    await io.homePage.addStep("*** Clicked on Create from scratch button ***");
    await io.flowBuilder.fill(selectors.basePagePO.NAME, "SALESFORCE");
    await io.homePage.addStep("*** Typed name for export ***");
    await io.flowBuilder.fill(selectors.connectionsPagePO.CONNECTION_INPUT, "SALESFORCE REALTIME CONNECTION");
    await io.homePage.clickByText("SALESFORCE REALTIME CONNECTION");
    await io.homePage.addStep("*** Selected salesforce connection ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.SF_SOBJECT_TYPE);
    await io.homePage.addStep("*** Clicked on selecting SOBJECT type ***");
    await io.homePage.clickByText("Account");
    await io.homePage.addStep("*** Selected SOBJECT type ***");
    await io.homePage.loadingTime();
    await io.homePage.loadingTime();
    await io.homePage.loadingTime();
    await io.flowBuilder.click(selectors.flowBuilderPagePO.EDIT_RELATED_LIST);
    await io.homePage.addStep("*** Clicked on edit related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ADD_NEW_RELATED_LIST);
    await io.homePage.addStep("*** Clicked on create new related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.CHILD_SOBJECT_TYPE);
    await io.homePage.addStep("*** Clicked on Select Child sobject type ***");
    await io.homePage.clickByText("AccountCleanInfos");
    await io.homePage.addStep("*** Selected Child sobject type ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ORDER_BY_FIELD);
    await io.homePage.addStep("*** Clicked on order field ***");
    await io.homePage.clickByText("Account ID");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ORDER);
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ASCENDING_ORDER);
    await io.homePage.addStep("*** Selected order field ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ADD_SELECTED);
    await io.homePage.addStep("*** Added related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.SAVE_RELATED_LIST);
    await io.homePage.addStep("*** Saved related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.EDIT_RELATED_LIST);
    await io.homePage.addStep("*** Clicked on edit related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.OPENACTIONSMENUATREFFEILD);
    await io.homePage.addStep("*** Clicked on actions button ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.APIMPUSHOPTION);
    await io.homePage.addStep("*** Clicked on edit related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.CHILD_SOBJECT_TYPE);
    await io.homePage.addStep("*** Clicked on Select Child sobject type ***");
    await io.homePage.clickByText("AccountContactRoles");
    await io.homePage.addStep("*** Selected Child sobject type ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.ADD_SELECTED);
    await io.homePage.addStep("*** Added related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.SAVE_RELATED_LIST);
    await io.homePage.addStep("*** Saved related list ***");
    await io.homePage.addStep("*** EDITED related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.EDIT_RELATED_LIST);
    await io.homePage.addStep("*** Clicked on edit related list ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.OPENACTIONSMENUATREFFEILD);
    await io.homePage.addStep("*** Clicked on actions button ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.CONFIRM_FLOW_GROUP_DELETE);
    await io.homePage.addStep("*** Clicked on delete button ***");
    await io.flowBuilder.click(selectors.flowBuilderPagePO.SAVE_RELATED_LIST);
    await io.homePage.addStep("*** Deleted related list ***");
    await io.myAccountPage.navigateTo(io.data.links.HOME_PAGE_URL);
    await io.homePage.addStep("*** Navigated to home page ***");
  });
});
