export class FlowBuilderPagePO {
  PAGE_GENERATOR = '[data-test="addGenerator"]';
  EXPORT_TRANSFORMATION = '[data-test="exportTransformation"]';
  TRANSFORM_GENERATE_MAP = '[data-test="generate-';
  TRANSFORM_DESTINATION_MAP = "#extract-";
  PAGE_PROCESSOR = '[data-test="addProcessor"]';
  DATA_PROCESSOR = '[data-test^="pp-"] [data-test="addDataProcessor"]';
  EXPORT_FILTER = '[data-test="exportFilter"]';
  FILTER_CONTAINER = 'select[name$="_filter"]';
  FILTER_OPERATOR = 'select[name$="_operator"]';
  FILTER_VALUE = 'input[name$="_value_0"]';
  EXPORT_HOOK = '[data-test="exportHooks"]';
  ADD_SCRIPT = '[data-test="preSavePage.script"]';
  SCRIPT_CONTENT = "#content-inline";
  SCRIPT_NAME = '[name="script-preSavePage"]';
  EXPORT_SCHEDULE = '[data-test="exportSchedule"]';
  EXPORT_SCHEDULE_START_TIME = '[data-test="startTime"]';
  EXPORT_SCHEDULE_END_TIME = '[data-test="endTime"]';
  APP_NAME_INPUT = '[data-test="application"] input[id*="react-select-"]';
  ADD_RULE = '[data-add="rule"]';
  DESTINATION_MAPPING = '[data-test="text-fieldMappingGenerate-';
  SOURCE_MAPPING = '[data-test="text-fieldMappingExtract-';
  TOGGLE_VIEW = '[id="toggle-view"]';
  ADD_SOURCE = '[data-test="Add source"]';
  ADD_DESTINATION_OR_LOOKUP = '[data-test="Add destination / lookup"]';
  EXPORT_TYPE = '[data-test="exportType"]';
  USE_EXISTING_EXPORT = '[data-test="checkExistingImport"] input';
  IMPORT_MAPPINGS = '[data-test="importMapping"]';
  MAPPER_2 = '[data-test="Mapper 2.0"]';
  FIELD_MAPPING_ADD = '[data-test*="fieldMappingAdd"]';
  OPEN_ACTIONS_MENU = '[data-test="openActionsMenu"]';
  DELETE_FLOW = '[data-test="deleteFlow"]';
  APPLICATION = '[data-test="application"]';
  CREATEFLOW = '[data-test="createFlow"]';
  MAPPER2_DESTINATION_FIELD_TEXT = '[data-test^="fieldMappingGenerate-"] input';
  MAPPER2_DESTINATION_FIELD_FIELD = 'textarea[class="MuiInputBase-input MuiFilledInput-input MuiInputBase-inputMultiline MuiFilledInput-inputMultiline"]';
  MAPPER2_SOURCE_FIELD_TEXT = '[id*="mapper2SourceTextField"]';
  MAPPER2_SOURCE_FIELD_FIELD = 'textarea[id*="mapper2SourceTextField"]';
  PREVIEW = '[data-test="previewEditorResult"]';
  FTP_FIELD_MAPPING_ADD = 'div:nth-child(2) > span > span > div > div > button';
  MAPPINGS_AREA = '[class="rc-tree-list-holder-inner"]';
  MAPPINGS_PREVIEW_RESULT_AREA = '[id="result"] [class="ace_layer ace_text-layer"]';
  FLOW_ENABLE = '[data-test="Enable"]';
  FLOW_DISABLE = '[data-test="Disable"]';
  FLOW_TOGGLE = '[class="react-toggle-thumb"]';
  RUN_FLOW = '[data-test="runFlow"]';
  FLOW_STATUS = '[class="MuiTypography-root MuiTypography-caption"]';
  JOB_NAME = 'tbody > tr > th';
  JOB_ERRORS = 'tbody > tr > td:nth-child(5) > button';
  LIST_VIEW_ERRORS = '[data-value="list"]';
  SPLIT_VIEW_ERRORS = '[data-value="split"]';
  LIST_VIEW_ERRORS_MESSAGE = 'div.MuiDrawer-paperAnchorRight.MuiPaper-elevation16 > div > div > div > div > div > table > tbody > tr > td:nth-child(2)';
  INCREASE_FLOW_BUILDER_BOTTOM_DRAWER = '[data-test="increaseFlowBuilderBottomDrawer"]';
  REFRESH_JOBS_BOARD = '[id="draggableSectionDivId"] [id="draggableSectionDivId"] div button:nth-child(2)';
  RESOLVED_ERRORS_TAB = '[data-test="flow-builder-resolved-errors"]';
  MAPPER2_TYPE_OR_SELECT_SOURCE_FIELD_TEXT = '[class$=" MuiPaper-elevation1 MuiPaper-rounded"] div ul';
  HTTP_FORM_SWITCH = '[data-test="HTTP"]';
  CHARTS = '[data-test="charts"]';
  FITVIEW = "(//div[@class='react-flow__controls']/button)[3]";
  CLOSE_RIGHT_DRAWER = "[data-test='closeRightDrawer']";
  ERROR_DATA = ".ace_layer.ace_text-layer div";
  COLUMNS = "tbody tr";
  REFRESH = ".MuiButton-label=Refresh";
  HEADER_STATUS = ".MuiButtonBase-root .MuiButton-label";
  TIME = '[aria-label="relative date time"]';
  JOBS_HEADER_ROW = ".MuiTableCell-root";
  JOBS_ROWS = "tr.MuiTableRow-hover";
  JOB_ERROR_NUMBERS = '[class$=" MuiButton-textPrimary MuiButton-disableElevation"]';
  ERROR_MESSAGE_CHECKBOX = 'th [class="MuiFormControlLabel-root"]';
}
